# Site settings
title: recenzjomat.pl
email: admin@recenzjomat.pl
description: > # this means to ignore newlines until "baseurl:"
  Jesteśmy źródłem recenzji produktów których szukasz.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Q
github_username: Q

# Build settings
markdown: kramdown
